spring.application.name=chatop
# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/chatop_db}
spring.datasource.username=${DB_USERNAME:customer}
spring.datasource.password=${DB_PASSWORD:mdpdefou}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
# JWT Configuration
jwt.secret.key=${JWT_SECRET_KEY:UILrLj2Wfc8ZIQnFv8qlluoZJMdO3A5l/jbLHSSu4Ow=}

